#!/bin/bash

# helper script to inform users of what is available

echo "[CarlaSeq pipeline]"
echo "For usage instructions see: https://docs.google.com/document/d/1yrYxkZAkjOikyyWmqwkPrqtd6gh0O3XHy_PwS7ybBxM"